version: '3'
services:
  muresearchui:
    image: "nginx:1.15"
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./:/var/muresearch_ui"
    restart: always
    networks: 
      - frontend

networks:
  frontend:
    driver: "bridge"